import { Accessibility, AudioLines, Check, Eye, Keyboard, RotateCcw, Volume2, VolumeX, Zap } from 'lucide-react'
import { GameShell } from '../components/layout/GameShell'
import { Panel } from '../components/ui/Panel'
import { GlowButton } from '../components/ui/GlowButton'
import { StatusPill } from '../components/ui/StatusPill'
import { useGameStore } from '../store/gameStore'
import type { MotionPreference } from '../types/game'

export function SettingsPage() {
  const settings = useGameStore((state) => state.settings)
  const setSettings = useGameStore((state) => state.setSettings)
  const resetGame = useGameStore((state) => state.resetGame)
  return (
    <GameShell title="SETTINGS" eyebrow="ACCESSIBILITY / EMERGENCY RESPONSE PREFERENCES" compact>
      <div className="mx-auto grid max-w-5xl gap-4 lg:grid-cols-[1fr_0.72fr]">
        <Panel eyebrow="ACCESSIBILITY" title="EMERGENCY RESPONSE INTERFACE"><div className="divide-y divide-white/10"><div className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center border border-cyan/30 bg-cyan/5 text-cyan"><Accessibility size={18} /></div><div><p className="text-sm font-semibold text-white">Motion</p><p className="micro-copy mt-1">Reduce route draw, rain and transition movement.</p></div></div><div className="flex gap-2">{(['FULL', 'REDUCED'] as MotionPreference[]).map((value) => <button type="button" key={value} onClick={() => setSettings({ motion: value })} className={`border px-3 py-2 font-mono text-[0.6rem] font-semibold tracking-[0.1em] transition ${settings.motion === value ? 'border-cyan/50 bg-cyan/10 text-cyan' : 'border-white/10 text-muted hover:text-white'}`} aria-pressed={settings.motion === value}>{value}</button>)}</div></div><div className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center border border-amber/30 bg-amber/5 text-amber">{settings.sound ? <Volume2 size={18} /> : <VolumeX size={18} />}</div><div><p className="text-sm font-semibold text-white">Sound</p><p className="micro-copy mt-1">Optional rain ambience and mission feedback.</p></div></div><button type="button" onClick={() => setSettings({ sound: !settings.sound })} className={`flex items-center gap-2 border px-3 py-2 font-mono text-[0.6rem] font-semibold tracking-[0.1em] transition ${settings.sound ? 'border-safe/50 bg-safe/10 text-safe' : 'border-white/10 text-muted hover:text-white'}`} aria-pressed={settings.sound}>{settings.sound ? <Check size={13} /> : <VolumeX size={13} />}{settings.sound ? 'ON' : 'OFF'}</button></div><div className="flex flex-col justify-between gap-4 p-5 sm:flex-row sm:items-center"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center border border-safe/30 bg-safe/5 text-safe"><Eye size={18} /></div><div><p className="text-sm font-semibold text-white">Color assistance</p><p className="micro-copy mt-1">Adds labels and extra contrast to semantic states.</p></div></div><button type="button" onClick={() => setSettings({ colorAssistance: !settings.colorAssistance })} className={`flex items-center gap-2 border px-3 py-2 font-mono text-[0.6rem] font-semibold tracking-[0.1em] transition ${settings.colorAssistance ? 'border-safe/50 bg-safe/10 text-safe' : 'border-white/10 text-muted hover:text-white'}`} aria-pressed={settings.colorAssistance}>{settings.colorAssistance ? <Check size={13} /> : <Eye size={13} />}{settings.colorAssistance ? 'ON' : 'OFF'}</button></div></div></Panel>
        <div className="space-y-4"><Panel eyebrow="SYSTEM STATUS" title="PREFERENCES ACTIVE"><div className="space-y-4 p-5"><StatusPill tone="safe">LOCAL STATE PERSISTED</StatusPill><div className="grid gap-3 border-t border-white/10 pt-4"><div className="flex items-center justify-between"><span className="micro-copy">MOTION PROFILE</span><span className="mono-value text-xs text-cyan">{settings.motion}</span></div><div className="flex items-center justify-between"><span className="micro-copy">SOUND</span><span className="mono-value text-xs text-amber">{settings.sound ? 'ON' : 'OFF'}</span></div><div className="flex items-center justify-between"><span className="micro-copy">COLOR ASSIST</span><span className="mono-value text-xs text-safe">{settings.colorAssistance ? 'ON' : 'OFF'}</span></div></div></div></Panel><Panel eyebrow="DEMO DATA" title="RESET LOCAL STATE"><div className="p-5"><p className="micro-copy leading-6">Reset the responder profile, emergency mission state, reports and demo controls to the seeded Zone 04 scenario.</p><GlowButton variant="secondary" className="mt-5 w-full" onClick={resetGame} icon={<RotateCcw size={15} />}>RESET DEMO STATE</GlowButton></div></Panel><Panel eyebrow="KEYBOARD READY" title="CONTROL NOTES"><div className="space-y-3 p-5"><div className="flex items-center gap-3"><Keyboard size={16} className="text-cyan" /><span className="micro-copy">Every primary action is keyboard focusable.</span></div><div className="flex items-center gap-3"><Zap size={16} className="text-amber" /><span className="micro-copy">Color is paired with text and icons.</span></div><div className="flex items-center gap-3"><AudioLines size={16} className="text-safe" /><span className="micro-copy">Sound is never required to understand alerts.</span></div></div></Panel></div>
      </div>
    </GameShell>
  )
}
